package com.rperez.weatherapp.data.local.db

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Data entity representing a temperature record in the database.
 * This entity holds weather-related values such as temperature, humidity, and air pressure,
 * and associates them with a city and date. Entries are indexed by date, city, temperature,
 * and description to ensure uniqueness and to minimize duplicate daily entries.
 *
 * @param id Unique identifier for the entry (auto-generated by Room).
 * @param date The date when the temperature record was recorded (formatted as "MMM d, yyyy").
 * @param city The city for which the temperature data is recorded.
 * @param desc A short description of the weather conditions (e.g., "sunny", "cloudy").
 * @param temperature The recorded temperature in degrees.
 * @param humidity The humidity level as a percentage.
 * @param pressure The atmospheric pressure in hPa (hectopascals).
 * @param timeStamp The system-generated timestamp of when the record was inserted (defaulted to current time).
 */
@Entity(
    tableName = "temperature",
    indices = [Index(value = ["date", "city", "temperature", "desc"], unique = true)]
)
data class TemperatureEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val date: String,
    val city: String,
    val desc: String,
    val temperature: Double,
    val humidity: Int,
    val pressure: Int,
    val timeStamp: Long = System.currentTimeMillis()
)
